In [38]:
import torch
torch.__version__
import numpy as np

In [5]:
x = torch.empty(3,3)
x

tensor([[-1.9826e-17,  4.5863e-41, -1.9826e-17],
        [ 4.5863e-41,  6.7709e+22,  3.3932e-09],
        [ 4.3025e-05,  5.5526e+31,  4.2964e+24]])

In [7]:
x = torch.rand(3,3)
x

tensor([[0.3298, 0.3751, 0.6005],
        [0.0810, 0.9865, 0.9370],
        [0.2381, 0.7997, 0.9218]])

In [9]:
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
x = torch.zeros(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.ones(3,3, dtype=torch.int32)
x.dtype

torch.int32

In [17]:
x.size()

torch.Size([3, 3])

In [19]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [22]:
x = torch.rand(2,2)
x

tensor([[0.6171, 0.8974],
        [0.2514, 0.6322]])

In [23]:
y = torch.rand(2,2)
y

tensor([[0.3715, 0.7416],
        [0.6551, 0.4397]])

In [24]:
y.add_(x)
y

tensor([[0.9887, 1.6389],
        [0.9065, 1.0720]])

In [25]:
y.sub_(x)
y

tensor([[0.3715, 0.7416],
        [0.6551, 0.4397]])

In [26]:
y.div_(x)
y

tensor([[0.6021, 0.8264],
        [2.6058, 0.6955]])

In [27]:
y.mul_(x)
y

tensor([[0.3715, 0.7416],
        [0.6551, 0.4397]])

In [29]:
y[1,1].item() # Take number

0.4397026300430298

In [37]:
y.view(4,-1) # reshape matrix

tensor([[0.3715],
        [0.7416],
        [0.6551],
        [0.4397]])

In [39]:
y.numpy()

array([[0.37154722, 0.74159145],
       [0.6550782 , 0.43970263]], dtype=float32)

In [44]:
a = np.ones(3)
a

array([1., 1., 1.])

In [46]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [47]:
if torch.cuda.is_available():
    device = torch.device("cuda")
device

device(type='cuda')

In [50]:
x = torch.ones(5, device='cuda')
x

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [51]:
x = torch.ones(5, device=device)
x

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [53]:
z = torch.ones(5)
z

tensor([1., 1., 1., 1., 1.])

In [55]:
z = z.to(device)
z

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [56]:
z = z.to("cuda")
z

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [60]:
z = z.to("cpu")
z

tensor([1., 1., 1., 1., 1.])

In [62]:
r = torch.ones(5, requires_grad=True)
r

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [126]:
x1 = torch.randn(3,requires_grad =True)
print(x1)
y1 = x1+2
print(y)
z1 = y1*y1*2
print(z1)
#z1 = z1.mean()
print(z1)

tensor([-0.4748,  0.2922, -0.4244], requires_grad=True)
tensor([2.1503, 2.9978, 0.6581], grad_fn=<AddBackward0>)
tensor([ 4.6523, 10.5082,  4.9649], grad_fn=<MulBackward0>)
tensor([ 4.6523, 10.5082,  4.9649], grad_fn=<MulBackward0>)


In [127]:
v = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
print(v)
z1.backward(v)
print(x1.grad)

tensor([0.1000, 1.0000, 0.0010])
tensor([6.1007e-01, 9.1687e+00, 6.3023e-03])


In [140]:
x = torch.randn(3,requires_grad =True)
x

tensor([-0.2309,  0.0500, -1.0290], requires_grad=True)

In [131]:
x.requires_grad_(False)

tensor([-1.4053, -2.3265,  1.7659])

In [134]:
y = x.detach()
y

tensor([-0.5699,  0.8612,  1.4649])

In [141]:
with torch.no_grad():
    y = x + 2
    print(y)
    print(x)

tensor([1.7691, 2.0500, 0.9710])
tensor([-0.2309,  0.0500, -1.0290], requires_grad=True)


In [143]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_() # This is important

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [145]:
weights = torch.ones(4, requires_grad=True)
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()